include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Controllers

Controllers_OBJC_FILES = AppController.m\
PlayListCtrllr.m\
PlayerCtrllr.m\
PreferencesController.m\
SettingsController.m\


ADDITIONAL_INCLUDE_DIRS += -I../ -I../Classes/

include $(GNUSTEP_MAKEFILES)/subproject.make
