include $(GNUSTEP_MAKEFILES)/common.make

SUBPROJECT_NAME = Classes

Classes_OBJC_FILES = MplayerInterface.m \
PlaylistTableView.m \
ScrubbingBar.m



ADDITIONAL_INCLUDE_DIRS += -I../ -I../Controllers/

include $(GNUSTEP_MAKEFILES)/subproject.make
